#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Record the TV program by JOB scheduler

Usage:
  rj [-h] add CH TITLE DATE TIME [RECORDINGTIME]
  rj [-h] list [DATE]
  rj [-h] show JOBID
  rj [-h] modbegin JOBID (DELTATIME | DATE TIME)

Options:
  -h --help   show this screen.

"""

from docopt import docopt
from recordjob.RecordJobTorque import RecordJobTorque

default_rectime = '00:29:30'

args = docopt(__doc__)
rec = RecordJobTorque()

if args['add']:
    """
    録画ジョブを追加する
    """

    if args['RECORDINGTIME']:
        rectime = args['RECORDINGTIME']
    else:
        rectime = default_rectime

    rec.add(args['CH'], args['TITLE'], args['DATE'], args['TIME'], rectime)

elif args['list']:
    """
    スケジュールされた録画ジョブを一覧表示する
    """
    rec.show(str_date=args['DATE'])

elif args['show']:
    """
    引数に指定されたIDのジョブを表示する
    """
    rec.show(jid=args['JOBID'])

elif args['modbegin']:
    """
    録画ジョブの開始時間を変更する
    """
    if args['DELTATIME']:
        rec.mod_begintime(args['JOBID'], args['DELTATIME'])
    else:
        print("not implemented yet")
        print("rec.mod_begintime({}, {}, {})".format(
            args['JOBID'],
            args['DATE'],
            args['TIME']))

